[package]
name = "lors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.1"
ordered-float = { version = "3.0", default-features = false }
num-traits = "0.2.15"
num-derive = "0.3.3"
